# Learning Numpy
---


In [1]:
import numpy as np

## creating array from list 
`np.array(list)`

In [2]:
array_1d = np.array([1,2,3,4,5])

print("1D array: ", array_1d)

1D array:  [1 2 3 4 5]


In [3]:
array_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

print("2D array: ",array_2d)

2D array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


## List vs numpy array

In [9]:
py_list = [1, 2, 3]

print("Pyhton list multiplication ", py_list*2)

Pyhton list multiplication  [1, 2, 3, 1, 2, 3]


In [ ]:
np_array = np.array([1, 2, 3])

print("Pyhton np_array multiplication ", np_array*2) # Element wise multiplicationn

Pyhton np_array multiplication  [2 4 6]


In [14]:
import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
# print(py_list)
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
# print(np_array)
print("\n Array operation time: ", time.time() - start)


 List operation time:  0.03857707977294922

 Array operation time:  0.00400853157043457


## creating array from scratch

In [28]:
zeros = np.zeros((3, 4)) # its like np.full((3,2), 0)
print("zeros array:\n", zeros)

ones = np.ones((3, 4)) # its like np.full((3,2), 1)
print("ones array:\n",ones)

full = np.full((2,2), 7) # its like np.full((row, column), number)
print("full array: \n", full)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]


In [14]:
random_py = np.random.random((2,3))
print("random array", (random_py* 10).astype(int)) # random array with row = 2,column = 3 array

random array [[9 6 2]
 [1 5 7]]


In [23]:
test = np.random.random((3,3))

print((test*10).astype(int))


[[3 5 9]
 [8 0 1]
 [1 7 3]]


In [25]:
test2  = np.array([2,2])

print(test2)

[2 2]


In [27]:
import tensorflow as tf